apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: my-cv
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: static
          nfs:
            server: diskstation.lan
            path: /volume1/docker_web/my_cv/static
      containers:
      - image: docker-registry.lan/django_cv_nginx
        volumeMounts:
          - name: static
            mountPath: /usr/src/app/django/my_cv/static
        name: nginx
        ports:
          - name: web
            containerPort: 80
            protocol: TCP
