apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: my-cv
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: static
          nfs:
            server: diskstation.lan
            path: /volume1/docker_web/my_cv/static
      containers:
      - image: docker-registry.lan/django_cv_web
        name: web
        command: ["gunicorn"]
        args: ["my_cv.wsgi", "--bind", "0.0.0.0:8000"]
        env:
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                 name: config-env-file
                 key: DEBUG
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                 name: config-env-file
                 key: SECRET_KEY
          - name: DJANGO_ALLOWED_HOSTS
            valueFrom:
              configMapKeyRef:
                 name: config-env-file
                 key: DJANGO_ALLOWED_HOSTS
        ports:
          - name: web
            containerPort: 8000
            protocol: TCP
