apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
  labels:
    apps: pgsql
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      volumes:
        - name: data
          nfs:
            server: diskstation.lan
            path: /volume1/docker_db/my_cv/data
      containers:
      - image: postgres
        name: postgres
        volumeMounts:
          - name: data
            mountPath: /var/lib/postgresql/data
        env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: config-env-file
                key: POSTGRES_PASSWORD
        ports:
          - name: postgres-port
            containerPort: 5432 

