# Setup configmap before applying this configuration
# configmap must have 
# DEBUG
# DJANGO_ALLOWED_HOSTS
# SECRET_KEY
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: web
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: my-cv
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: static
          nfs:
            server: diskstation.lan
            path: /volume1/docker_web/my_cv/static
      containers:
      - image: docker-registry.lan/django_cv_web
        name: web
        command: ["gunicorn"]
        args: ["my_cv.wsgi", "--bind", "0.0.0.0:8000"]
        env:
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                 name: config-env-file
                 key: DEBUG
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                 name: config-env-file
                 key: SECRET_KEY
          - name: DJANGO_ALLOWED_HOSTS
            valueFrom:
              configMapKeyRef:
                 name: config-env-file
                 key: DJANGO_ALLOWED_HOSTS
        ports:
          - name: web
            containerPort: 8000
            protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: my-cv
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: static
          nfs:
            server: diskstation.lan
            path: /volume1/docker_web/my_cv/static
      containers:
      - image: docker-registry.lan/django_cv_nginx
        volumeMounts:
          - name: static
            mountPath: /usr/src/app/django/my_cv/static
        name: nginx
        ports:
          - name: web
            containerPort: 80
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
