apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metallb.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.50-192.168.1.60
